### ISSUE TITLE
Tracing : avoid some span to be exportable

### ISSUE THREAD

**Issue by chsi13** [p6spy/p6spy#472]
Hi. 

I trace db statements with p6spy and spring cloud sleuth. It exports connection , query and fetch spans...Is it possible to only export to zipkin query statements ???

**Comment by gavlyukovskiy** [comment]
Hi, I see you've created and closed later issue in my project https://github.com/gavlyukovskiy/spring-boot-data-source-decorator/issues/34. It was the right place since spring boot starter is not maintained here. 
Currently there is no way to disable those spans, but most probably I can implement that if you're still interested.

**Comment by chsi13** [comment]
Hello. Yes I find interesting to only keep "query" spans and so exclude connection and fetch spans from traces :-).

**Comment by gavlyukovskiy** [comment]
@chsi13 I've made changes in scope of original issue in my repository. It will be available in upcoming release of starter.
