### ISSUE TITLE
How to interpret `jdbc:/datasource/connection`

### ISSUE THREAD

**Issue by devansh-dalal** [p6spy/p6spy#510]
We have been using spring cloud sleuth in our micoservices for tracing. We have also added enabled jdbc level spans from spring data Repository connection, fetch and query. I am seeing some weird jps traces of name `jdbc:/datasource/connection` which seem to include some of my service specific spans. I was of the view that a parent span includes only those spans as kids, which it calls. 

![Screenshot 2020-09-26 at 17 16 49](https://user-images.githubusercontent.com/69784585/94364784-8396a500-00e9-11eb-8e9b-6f72773e8cea.png)

`venderproxy`, `profile`:`fetchorganization` are my other services' grpc endpoints, why is `jdbc:/datasource/connection` span in `supplier` including some of my services under it?

**Comment by gavlyukovskiy** [comment]
It looks like this issue is more suitable for https://github.com/gavlyukovskiy/spring-boot-data-source-decorator that provides such integration. But I can't move it there so let me answer here.

`jdbc:/datasource/connection` span represents open connection (transaction), in this case you're most likely haven't closed the connection and calling other services? For example you might be calling other services from the method annotated with `@Transactional`. While it might be ok for some scenarios, it can cause issues with connection pool if you're holding connection open for 5s.

**Comment by devansh-dalal** [comment]
@gavlyukovskiy, yeah, your explanation fits perfectly here. We were actually using `@Transactional` on the function where the `jdbc:/datasource/connection` span starts. This warning also aptly suits up for us: `While it might be ok for some scenarios, it can cause issues with connection pool if you're holding connection open for 12s.`. Thanks for answering.
